server:
  port: 8888

spring:
  application:
    name: popool-config-service

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: git@github.com:HyuckJuneHong/git-local-config.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIApv3LXFtHNXjxhNSMY5X86/o0bLnvu3Eqj5KD6qacT8oAoGCCqGSM49
            AwEHoUQDQgAEFhC028LT7Nor00kKF+2NGafQA4o3kKx9rP+bCjvwwRNKchgWLTO2
            6wZhlbGKZv/HkrgblvZpACn6GMnYqmvKNg==
            -----END EC PRIVATE KEY-----
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
